name: Main Workflow - Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-on-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run Chrome Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true
          publish-summary: true

      - name: Chrome - Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Chrome - Test Report
          path: cypress/reports
          if-no-files-found: ignore
  
  run-on-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest
      
      - name: Run Firefox Tests
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          headed: true
          publish-summary: true

      - name: Firefox - Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Firefox - Test Report
          path: cypress/reports
          if-no-files-found: ignore
